version: "3.8"

services:
  frontend:
    build: ./src/frontend
    ports:
      - "8331:80"
    depends_on:
      - backend
    networks:
    - app-network

  backend:
    build: ./src/backend
    ports:
      - "8332:8443"
    depends_on:
      - database
    networks:
      - app-network
  database:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=my_database
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network
  
volumes:
  db-data:

networks:
  app-network:
    driver: bridge