version: "3.8"

services:
  omicron_frontend:
    build: ./src/frontend
    ports:
      - "7000:7000"
    depends_on:
      - omicron_backend
    networks:
      - main

  omicron_backend:
    build: ./src/backend
    ports:
      - "6000:6000"
    depends_on:
      - omicron_database
    networks:
      - main

  omicron_database:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=my_database
    volumes:
      - omicron:/var/lib/mysql  
    networks:
      - main

volumes:
  omicron: 
    external: true 

networks:
  main:
    external: true 