version: "3.8"

services:
  frontend:
    build: ./src/frontend
    ports:
      - "8000:80"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:8443  # Use service name instead of localhost

  backend:
    build: ./src/backend
    ports:
      - "8001:8443"
    depends_on:
      - database

  database:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=my_database
    volumes:
      - db-data:/var/lib/mysql  # Use standard MariaDB data directory

volumes:
  db-data: