[package]
name = "omicron-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
env_logger = "0.11.6"
once_cell = "1.20.2"
sqlx = { version = "0.8.3", features = [ "runtime-tokio", "mysql" ] }
tokio = { version = "1.43.0", features = ["full"] }